goals:
- id: 1
  name: Waypoint_1
  description: 'Candidate destination #1 recorded via interactive HUD'
  x_m: 4.25
  y_m: -2.1
  z_m: 0.2
  yaw_deg: 9.7
  tolerance_m: 0.5
  snapshot_image: config/goals/goal_01_Waypoint_1.jpg
- id: 2
  name: Waypoint_2
  description: 'Candidate destination #2 recorded via interactive HUD'
  x_m: 10.58
  y_m: -0.02
  z_m: 0.49
  yaw_deg: -19.1
  tolerance_m: 0.5
  snapshot_image: config/goals/goal_02_Waypoint_2.jpg
- id: 3
  name: Waypoint_3
  description: 'Candidate destination #3 recorded via interactive HUD'
  x_m: 9.73
  y_m: -4.76
  z_m: 0.45
  yaw_deg: -47.4
  tolerance_m: 0.5
  snapshot_image: config/goals/goal_03_Waypoint_3.jpg
- id: 4
  name: Waypoint_4
  description: 'Candidate destination #4 recorded via interactive HUD'
  x_m: 12.93
  y_m: -4.42
  z_m: 0.59
  yaw_deg: 15.2
  tolerance_m: 0.5
  snapshot_image: config/goals/goal_04_Waypoint_4.jpg
